# Generated by Django 4.1.5 on 2023-01-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('house_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адресы',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя завода')),
                ('staff', models.IntegerField()),
                ('debt', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contacts', models.ManyToManyField(to='core.contact')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя продукта')),
                ('model', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='RetailChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя крупной розничной сети')),
                ('staff', models.IntegerField()),
                ('debt', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contacts', models.ManyToManyField(to='core.contact')),
                ('products', models.ManyToManyField(to='core.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.factory')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя индивидуально предпринимателя')),
                ('staff', models.IntegerField()),
                ('debt', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contacts', models.ManyToManyField(to='core.contact')),
                ('products', models.ManyToManyField(to='core.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.retailchain')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
        ),
        migrations.AddField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(to='core.product'),
        ),
    ]
