# Generated by Django 4.1.5 on 2023-01-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_factory_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='retailchain',
            name='staff',
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default='default', max_length=30, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(default='default', max_length=30, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='house_number',
            field=models.IntegerField(default=1, verbose_name='Номер дома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(default='default', max_length=30, verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factory',
            name='contacts',
            field=models.ManyToManyField(to='core.contact', verbose_name='Данные контактов'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название завода'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(to='core.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='contacts',
            field=models.ManyToManyField(to='core.contact', verbose_name='Данные контактов'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='debt',
            field=models.FloatField(verbose_name='Задолженность перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='products',
            field=models.ManyToManyField(to='core.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.retailchain', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='retailchain',
            name='contacts',
            field=models.ManyToManyField(to='core.contact', verbose_name='Данные контактов'),
        ),
        migrations.AlterField(
            model_name='retailchain',
            name='debt',
            field=models.FloatField(verbose_name='Задолженность перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='retailchain',
            name='products',
            field=models.ManyToManyField(to='core.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='retailchain',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.factory', verbose_name='Поставщик'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
