# Generated by Django 4.1.5 on 2023-01-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_contact_address_remove_factory_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='city',
            field=models.CharField(default='Санкт-Петербург', max_length=30, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factory',
            name='country',
            field=models.CharField(default='Россия', max_length=30, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factory',
            name='house_number',
            field=models.IntegerField(default=17, verbose_name='Номер дома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factory',
            name='street',
            field=models.CharField(default='Титова', max_length=30, verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='city',
            field=models.CharField(default='Санкт-Петербург', max_length=30, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='country',
            field=models.CharField(default='Россия', max_length=30, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='house_number',
            field=models.IntegerField(default=12, verbose_name='Номер дома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='street',
            field=models.CharField(default='Богдана Хмельнинского', max_length=30, verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailchain',
            name='city',
            field=models.CharField(default='Иркутск', max_length=30, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailchain',
            name='country',
            field=models.CharField(default='Россия', max_length=30, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailchain',
            name='house_number',
            field=models.IntegerField(default=16, verbose_name='Номер дома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailchain',
            name='street',
            field=models.CharField(default='Пушкинская', max_length=30, verbose_name='Улица'),
            preserve_default=False,
        ),
    ]
